server:
  port: 8080

# Spring Datasource configuration
spring:
  datasource:
    url: jdbc:h2:mem:myshopdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  # H2 Console configuration
  h2:
    console:
      enabled: true
  # JPA/Hibernate configuration
  jpa:
    hibernate:
      # Automatically update the database schema based on entities
      ddl-auto: update
    # Log SQL statements to the console for debugging
    show-sql: true
    properties:
      hibernate:
        # Format the logged SQL to be more readable
        format_sql: true

# Swagger/OpenAPI configuration
springdoc:
  swagger-ui:
    # Sets the custom path for the Swagger UI page
    path: /swagger