package com.skcodify.myshop.mapper;

import java.util.stream.Collectors;
import org.springframework.stereotype.Component;

import com.skcodify.myshop.domain.Society;
import com.skcodify.myshop.domain.User;
import com.skcodify.myshop.dto.SocietyDto;
import com.skcodify.myshop.dto.UserDto;

@Component
public class UserMapper {

    public UserDto toDto(User user) {
        if (user == null) {
            return null;
        }

        UserDto dto = new UserDto();
        dto.setId(user.getId());
        dto.setName(user.getName());
        dto.setApartmentNumber(user.getApartmentNumber());
        dto.setEmail(user.getEmail());
        dto.setPhone(user.getPhone());
        dto.setUserType(user.getUserType());
        dto.setShopName(user.getShopName());
        dto.setVerified(user.isVerified());
        dto.setBlocked(user.isBlocked());

        if (user.getBuyerSociety() != null) {
            SocietyDto sDto = new SocietyDto();
            sDto.setId(user.getBuyerSociety().getId());
            sDto.setName(user.getBuyerSociety().getName());
            sDto.setArea(user.getBuyerSociety().getArea());
            dto.setBuyerSociety(sDto);
        }

        if (user.getServiceSocieties() != null) {
            dto.setServiceSocieties(user.getServiceSocieties().stream()
                .map(society -> {
                    SocietyDto sDto = new SocietyDto();
                    sDto.setId(society.getId());
                    sDto.setName(society.getName());
                    sDto.setArea(society.getArea());
                    return sDto;
                })
                .collect(Collectors.toSet())
            );
        }

        return dto;
    }

    public User toEntity(UserDto dto) {
        if (dto == null) {
            return null;
        }

        User user = new User();
        // ID is usually generated by the database for new entities, so we don't set it here.
        // If you're using UUIDs generated on the client or service layer, you might set it.
        user.setName(dto.getName());
        user.setApartmentNumber(dto.getApartmentNumber());
        user.setEmail(dto.getEmail());
        user.setPhone(dto.getPhone());
        user.setUserType(dto.getUserType());
        user.setShopName(dto.getShopName());
        user.setVerified(dto.isVerified());
        user.setBlocked(dto.isBlocked());

        if (dto.getBuyerSociety() != null) {
            Society society = new Society();
            society.setId(dto.getBuyerSociety().getId());
            society.setName(dto.getBuyerSociety().getName());
            society.setArea(dto.getBuyerSociety().getArea());
            user.setBuyerSociety(society);
        }

        if (dto.getServiceSocieties() != null) {
            user.setServiceSocieties(dto.getServiceSocieties().stream()
                .map(sDto -> {
                    Society society = new Society();
                    society.setId(sDto.getId());
                    society.setName(sDto.getName());
                    society.setArea(sDto.getArea());
                    return society;
                })
                .collect(Collectors.toSet())
            );
        }
        return user;
    }
}