package com.skcodify.myshop.mapper;

import org.springframework.stereotype.Component;

import com.skcodify.myshop.domain.User;
import com.skcodify.myshop.dto.UserDto;

@Component
public class UserMapper {

    public UserDto toDto(User user) {
        if (user == null) {
            return null;
        }

        UserDto dto = new UserDto();
        dto.setId(user.getId());
        dto.setName(user.getName());
        dto.setApartmentNumber(user.getApartmentNumber());
        dto.setEmail(user.getEmail());
        dto.setPhone(user.getPhone());
        dto.setUserType(user.getUserType());
        dto.setShopName(user.getShopName());
        dto.setVerified(user.isVerified());
        dto.setBlocked(user.isBlocked());

        return dto;
    }

    public User toEntity(UserDto dto) {
        if (dto == null) {
            return null;
        }

        User user = new User();
        // ID is usually generated by the database for new entities, so we don't set it here.
        // If you're using UUIDs generated on the client or service layer, you might set it.
        user.setName(dto.getName());
        user.setApartmentNumber(dto.getApartmentNumber());
        user.setEmail(dto.getEmail());
        user.setPhone(dto.getPhone());
        user.setUserType(dto.getUserType());
        user.setShopName(dto.getShopName());
        user.setVerified(dto.isVerified());
        user.setBlocked(dto.isBlocked());
        return user;
    }
}